// Job DSL definitions for Jenkins Remoting validation pipelines

pipelineJob('01-linux-ssh-build') {
    description('Test workload execution on remote Linux SSH Agent with isolated environment')
    definition {
        cps {
            sandbox(true)
            script("""
pipeline {
    agent {
        node {
            label 'ssh'
        }
    }
    stages {
        stage('Node Identification') {
            steps {
                echo '=== Executing on Remote SSH Agent ==='
                sh 'uname -a'
                sh 'whoami'
                sh 'pwd'
                sh 'java -version'
            }
        }
        stage('Environment Isolation Check') {
            steps {
                sh 'echo "Hostname: \$(hostname)"'
                sh 'echo "Current User ID: \$(id -u) (Group: \$(id -g))"'
            }
        }
        stage('Simulate Build Workload') {
            steps {
                sh 'mkdir -p build_output'
                sh 'date > build_output/build_info.txt'
                sh 'echo "Artifact generated by SSH Remoting Node" >> build_output/build_info.txt'
                sh 'cat build_output/build_info.txt'
            }
        }
    }
    post {
        success {
            echo 'SSH Node Execution Completed Successfully!'
        }
    }
}
""".stripIndent())
        }
    }
}

pipelineJob('02-linux-inbound-build') {
    description('Test workload execution on remote Linux Inbound/JNLP Agent')
    definition {
        cps {
            sandbox(true)
            script("""
pipeline {
    agent {
        node {
            label 'inbound-agent'
        }
    }
    stages {
        stage('Inbound Node Identification') {
            steps {
                echo '=== Executing on Remote Inbound (JNLP) Agent ==='
                sh 'uname -a'
                sh 'whoami'
                sh 'pwd'
                sh 'java -version'
            }
        }
        stage('Network & Protocol Verification') {
            steps {
                sh 'echo "Hostname: \$(hostname)"'
                sh 'echo "Agent Directory Contents:"'
                sh 'ls -la'
            }
        }
        stage('Execute Inbound Payload') {
            steps {
                sh 'mkdir -p results'
                sh 'echo "Processed via Inbound Protocol at \$(date)" > results/inbound_summary.txt'
                sh 'cat results/inbound_summary.txt'
            }
        }
    }
    post {
        success {
            echo 'Inbound Node Execution Completed Successfully!'
        }
    }
}
""".stripIndent())
        }
    }
}

pipelineJob('03-distributed-multi-arch-matrix') {
    description('Concurrent distributed execution across multiple remote architectures to test load balancing & isolation')
    definition {
        cps {
            sandbox(true)
            script("""
pipeline {
    agent none
    stages {
        stage('Parallel Distributed Workloads') {
            parallel {
                stage('Branch A: Linux SSH Node') {
                    agent {
                        node {
                            label 'ssh'
                        }
                    }
                    stages {
                        stage('SSH Worker Task') {
                            steps {
                                echo "SSH Worker Task starting on \${env.NODE_NAME}"
                                sh 'echo "Node: \$(hostname) / Arch: \$(uname -m)"'
                                sh 'sleep 3'
                                echo 'SSH Task completed.'
                            }
                        }
                    }
                }
                stage('Branch B: Linux Inbound Node') {
                    agent {
                        node {
                            label 'inbound-agent'
                        }
                    }
                    stages {
                        stage('Inbound Worker Task') {
                            steps {
                                echo "Inbound Worker Task starting on \${env.NODE_NAME}"
                                sh 'echo "Node: \$(hostname) / Arch: \$(uname -m)"'
                                sh 'sleep 3'
                                echo 'Inbound Task completed.'
                            }
                        }
                    }
                }
            }
        }
        stage('Master Verification Summary') {
            agent {
                node {
                    label 'ssh || inbound-agent'
                }
            }
            steps {
                echo '=== Multi-Arch Remoting Matrix Completed Successfully ==='
                echo 'Both remote nodes processed tasks concurrently with complete isolation.'
            }
        }
    }
}
""".stripIndent())
        }
    }
}
